[package]
name = "contact_list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
aws-config = "1.1.9"
aws-sdk-sesv2 = "1.19.0"
tokio = "1.37.0"
tracing-subscriber = "0.3.18"
