/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example

import aws.sdk.kotlin.services.sesv2.SesV2Client
import aws.sdk.kotlin.services.sesv2.model.CreateContactListRequest
import aws.sdk.kotlin.services.sesv2.model.DeleteContactListRequest
import aws.sdk.kotlin.services.sesv2.model.ListContactsRequest

private const val CONTACT_LIST_NAME = "weekly-coupons-newsletter" // Replace with your contact list name

suspend fun main() {
    SesV2Client { region = "us-east-1" }.use { sesClient ->
        sesClient.createContactList( CreateContactListRequest { contactListName = CONTACT_LIST_NAME })
        println("Created contact list")
        val contactListResponse = sesClient.listContacts(ListContactsRequest { contactListName = CONTACT_LIST_NAME })
        println("Contacts: ${contactListResponse.contacts}")
        sesClient.deleteContactList(DeleteContactListRequest { contactListName = CONTACT_LIST_NAME })
        println("Deleted contact list")
    }
}
